apiVersion: v1
kind: Service
metadata:
  name: webhook-server
  namespace: monitoring
spec:
  selector:
    app: webhook-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
