global:
  resolve_timeout: 5m

route:
  receiver: 'default-receiver'
  routes:
  - match:
      severity: 'critical'
    receiver: 'critical-receiver'
  
receivers:
- name: 'default-receiver'
  webhook_configs:
  - url: 'http://aa7c2d81c08b34d82a4dd7a125f55339-1689132779.ap-south-1.elb.amazonaws.com/'
- name: 'critical-receiver'
  webhook_configs:
  - url: 'http://aa7c2d81c08b34d82a4dd7a125f55339-1689132779.ap-south-1.elb.amazonaws.com/'
